#!/bin/bash
# Startup script for shared_memory_mcp
# Generated by Pulser Bootstrap

set -e

echo "🚀 Starting shared_memory_mcp..."

# Navigate to server directory
cd "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/mcp/shared_memory_mcp"

# Activate virtual environment if it exists
if [ -d "venv" ]; then
    echo "📦 Activating virtual environment..."
    source venv/bin/activate
fi

# Install dependencies if requirements.txt exists
if [ -f "requirements.txt" ]; then
    echo "📚 Installing dependencies..."
    pip install -r requirements.txt
fi

# Start the server
echo "▶️ Starting server on port 5700..."
python /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/mcp/shared_memory_mcp/src/memory_server.py
