#!/bin/bash
# Stop all MCP servers
# Generated by Pulser Bootstrap

echo "🛑 Stopping all MCP servers..."

# Kill servers using PID files
if [ -d "pids" ]; then
    for pid_file in pids/*.pid; do
        if [ -f "$pid_file" ]; then
            pid=$(cat "$pid_file")
            server_name=$(basename "$pid_file" .pid)
            
            if kill -0 "$pid" 2>/dev/null; then
                echo "🔴 Stopping $server_name (PID: $pid)"
                kill "$pid"
                rm "$pid_file"
            else
                echo "⚠️ $server_name was not running"
                rm "$pid_file"
            fi
        fi
    done
fi

echo "✅ All servers stopped"
