name: Publish npm Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish'
        required: true
        default: '4.0.0'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run type checking
      run: npm run typecheck
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Build package
      run: npm run build
    
    - name: Create tarball and check
      run: |
        npm pack
        tar -tf pulser-sdk-*.tgz
    
    - name: Publish to npm (dry run)
      run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Publish to npm
      if: github.event_name == 'release' || github.event.inputs.version != ''
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub Release Assets
      if: github.event_name == 'release'
      run: |
        for file in pulser-sdk-*.tgz; do
          gh release upload ${{ github.event.release.tag_name }} "$file"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag with latest
      if: github.event_name == 'release'
      run: |
        npm dist-tag add pulser-sdk@${{ github.event.release.tag_name }} latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}